### ISSUE TITLE
Update README to include a canonical "Hello World" element example

### ISSUE THREAD

**Issue by klebba** [Netflix/x-element#247]
E.g.

```javascript
// hello-element.js
import XElement from 'https://deno.land/x/element/x-element.js';
import styleSheet from './hello-world.css' with { type: 'css' };

class HelloElement extends XElement {
  static get properties() {
    return {
      subject: {
        type: String,
        initial: 'World',
      },
    };
  }

  static get styles() {
    return [styleSheet];
  }

  static template(html) {
    return ({ subject }) => html`
      Hello ${subject}!
    `;
  }
}

customElements.define('hello-element', HelloElement);
```

```css
/* hello-element.css */
:host {
  display: inline-block;
  background-color: cyan;
  border-radius: 100vmax;
}
```

```html
<!-- demo.html -->
<html>
  <head>
    <title>hello-world demo</title>
    <script type="module" src="./hello-element.js"></script>
  </head>
  <body>
    <hello-element subject="Nurse"></hello-element>
    <hello-element subject="Dolly"></hello-element>
    <hello-element subject="I Love You"></hello-element>
  </body>
</html>
```
